apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ecommerce.name }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ecommerce.type }}
  ports:
    - port: {{ .Values.ecommerce.port }}
      targetPort: {{ .Values.ecommerce.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
