apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.mongo.name }}"
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.mongo.name }}"
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: "{{ .Values.mongo.name }}"
    spec:
      containers:
        - name: "{{ .Values.mongo.name }}"
          image: "{{ .Values.mongo.name }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mongo.port }}
              protocol: TCP
