apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
spec:
  type: {{ .Values.mongo.type }}
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.mongo.name }}
